debug: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123!@#
    url: jdbc:mysql://localhost:3306/web_todo

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework: info
    com.sparta: debug
jwt:
  secret: hello1234567890